

[fsps_full]
    files = [
        'fsps_full/tweak_fsps_QSF_12_v3_001.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_002.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_003.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_004.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_005.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_006.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_007.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_008.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_009.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_010.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_011.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_012.dat',
    ]
    attribution = "eazy, fsps"

[fsps_Larson22]
    files = [
        'fsps_full/tweak_fsps_QSF_12_v3_001.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_002.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_003.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_004.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_005.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_006.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_007.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_008.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_009.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_010.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_011.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_012.dat',
        'Larson22/binc100z001age6_cloudy.dat',
        'Larson22/binc100z001age65_cloudy.dat',
        'Larson22/binc100z001age7_cloudy.dat',
    ]
    attribution = "fsps, Larson et al. (2022)"


[sfhz]
    files = [
        'sfhz/corr_sfhz_13_bin3_av0.50.fits',
        'sfhz/corr_sfhz_13_bin3_av0.01.fits',
        'sfhz/corr_sfhz_13_bin2_av1.00.fits',
        'sfhz/corr_sfhz_13_bin2_av0.50.fits',
        'sfhz/corr_sfhz_13_bin2_av0.01.fits',
        'sfhz/corr_sfhz_13_bin1_av1.00.fits',
        'sfhz/corr_sfhz_13_bin1_av0.50.fits',
        'sfhz/corr_sfhz_13_bin1_av0.25.fits',
        'sfhz/corr_sfhz_13_bin1_av0.01.fits',
        'sfhz/corr_sfhz_13_bin0_av1.00.fits',
        'sfhz/corr_sfhz_13_bin0_av0.50.fits',
        'sfhz/corr_sfhz_13_bin0_av0.25.fits',
        'sfhz/corr_sfhz_13_bin0_av0.01.fits',
    ]
    attribution = "eazy, fsps, Gabe Brammer"


[sfhz_Larson22]
    files = [
        'sfhz/corr_sfhz_13_bin3_av0.50.fits',
        'sfhz/corr_sfhz_13_bin3_av0.01.fits',
        'sfhz/corr_sfhz_13_bin2_av1.00.fits',
        'sfhz/corr_sfhz_13_bin2_av0.50.fits',
        'sfhz/corr_sfhz_13_bin2_av0.01.fits',
        'sfhz/corr_sfhz_13_bin1_av1.00.fits',
        'sfhz/corr_sfhz_13_bin1_av0.50.fits',
        'sfhz/corr_sfhz_13_bin1_av0.25.fits',
        'sfhz/corr_sfhz_13_bin1_av0.01.fits',
        'sfhz/corr_sfhz_13_bin0_av1.00.fits',
        'sfhz/corr_sfhz_13_bin0_av0.50.fits',
        'sfhz/corr_sfhz_13_bin0_av0.25.fits',
        'sfhz/corr_sfhz_13_bin0_av0.01.fits',
        'Larson22/binc100z001age6.dat',
        'Larson22/binc100z001age6_cloudy.dat',
    ]
    attribution = "eazy, fsps, Gabe Brammer, Larson et al. (2022)"